"""first init

Revision ID: bfb4b95c2311
Revises:
Create Date: 2025-05-08 23:11:44.479214

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bfb4b95c2311"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop enum types
    op.execute("DROP TYPE IF EXISTS serviceenum")
    op.execute("DROP TYPE IF EXISTS jobenum")

    op.create_table(
        "job",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("url", sa.String(length=255), nullable=False),
        sa.Column("args", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "service", sa.Enum("TRADING_ASSISTANT", name="serviceenum"), nullable=False
        ),
        sa.Column("cron_expression", sa.String(length=100), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("next_run", sa.DateTime(timezone=True), nullable=True),
        sa.Column("scheduler_id", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=100), nullable=False),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="job-management",
    )
    op.create_index(
        op.f("ix_job-management_job_id"),
        "job",
        ["id"],
        unique=False,
        schema="job-management",
    )
    op.create_table(
        "job_history",
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column(
            "status", sa.Enum("SUCCESS", "FAILURE", name="jobenum"), nullable=False
        ),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=100), nullable=False),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"], ["job-management.job.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="job-management",
    )
    op.create_index(
        op.f("ix_job-management_job_history_id"),
        "job_history",
        ["id"],
        unique=False,
        schema="job-management",
    )
    op.create_index(
        op.f("ix_job-management_job_history_job_id"),
        "job_history",
        ["job_id"],
        unique=False,
        schema="job-management",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_job-management_job_history_job_id"),
        table_name="job_history",
        schema="job-management",
    )
    op.drop_index(
        op.f("ix_job-management_job_history_id"),
        table_name="job_history",
        schema="job-management",
    )
    op.drop_table("job_history", schema="job-management")
    op.drop_index(
        op.f("ix_job-management_job_id"), table_name="job", schema="job-management"
    )
    op.drop_table("job", schema="job-management")
    # ### end Alembic commands ###
